//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Thompson.RecordSearch.Utility.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Thompson.RecordSearch.Utility.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///	&quot;web&quot;: &quot;https://oxfordlegalleads.com/app/get-county-code&quot;,
        ///	&quot;counties&quot;: 
        ///		[
        ///			{
        ///			&quot;id&quot;: 60,
        ///			&quot;name&quot;: &quot;dallas&quot;,
        ///			&quot;code&quot;: &quot;legal.lead.dallas.uindex&quot;,
        ///			&quot;vector&quot;: &quot;04fvxOSLb7yEYgBPQCR0Gw==&quot;
        ///			}
        ///		]
        ///}.
        /// </summary>
        internal static string credential_service_map {
            get {
                return ResourceManager.GetString("credential_service_map", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [
        ///	{
        ///		&quot;name&quot;: &quot;county&quot;,
        ///		&quot;items&quot;: [
        ///			{
        ///				&quot;id&quot;: 1,
        ///				&quot;name&quot;: &quot;County Court at Law No. 1&quot;,
        ///				&quot;address&quot;: [
        ///					&quot;County Court at Law No. 1&quot;,
        ///					&quot;George L. Allen, Sr. Courts Building&quot;,
        ///					&quot;600 Commerce Street&quot;,
        ///					&quot;Dallas, TX 75202&quot;
        ///				]
        ///			},
        ///			{
        ///				&quot;id&quot;: 2,
        ///				&quot;name&quot;: &quot;County Court at Law No. 2&quot;,
        ///				&quot;address&quot;: [
        ///					&quot;County Court at Law No. 2&quot;,
        ///					&quot;George L. Allen, Sr. Courts Building&quot;,
        ///					&quot;600 Commerce Street&quot;,
        ///					&quot;Dallas, TX 75202&quot;
        ///				]
        ///			},
        ///			{
        ///				&quot;i [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string dallas_court_address {
            get {
                return ResourceManager.GetString("dallas_court_address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [
        ///	{
        ///		&quot;name&quot;: &quot;county&quot;,
        ///		&quot;items&quot;: [
        ///			{
        ///				&quot;id&quot;: 1,
        ///				&quot;name&quot;: &quot;County Court at Law No. 1&quot;,
        ///				&quot;address&quot;: [
        ///					&quot;County Court at Law No. 1&quot;,
        ///					&quot;1700 Guadalupe, Austin, TX 78701&quot;
        ///				]
        ///			},
        ///			{
        ///				&quot;id&quot;: 2,
        ///				&quot;name&quot;: &quot;County Court at Law No. 2&quot;,
        ///				&quot;address&quot;: [
        ///					&quot;County Court at Law No. 2&quot;,
        ///					&quot;1700 Guadalupe, Austin, TX 78701&quot;
        ///				]
        ///			}
        ///		]
        ///	},
        ///	{
        ///		&quot;name&quot;: &quot;justice&quot;,
        ///		&quot;items&quot;: [
        ///			{
        ///				&quot;id&quot;: 1,
        ///				&quot;name&quot;: &quot;Precinct 1&quot;,
        ///				&quot;address&quot;: [
        ///					&quot;Justice of [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string travis_court_address {
            get {
                return ResourceManager.GetString("travis_court_address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///	&quot;url-county&quot;: &quot;https://odysseyweb.traviscountytx.gov/Portal/&quot;,
        ///	&quot;url-district&quot;: &quot;https://odysseyweb.traviscountytx.gov/Portal/&quot;,
        ///	&quot;url-justice&quot;: &quot;https://odysseypa.traviscountytx.gov/JPPublicAccess/default.aspx&quot;,
        ///	&quot;searchLink&quot;: &quot;//a[@class=&apos;ssSearchHyperlink&apos;][contains(text(), &apos;Civil&apos;)]&quot;
        ///}.
        /// </summary>
        internal static string travis_navigation {
            get {
                return ResourceManager.GetString("travis_navigation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~ select search by case
        ///var colinput = Array.prototype.slice.call( document.getElementsByTagName(&apos;input&apos;), 0 );
        ///
        ///var colstatus = colinput.filter(x =&gt; { 
        ///let attr = x.getAttribute(&apos;name&apos;); 
        ///if ( attr == null ) { return false; } 
        ///return attr == &apos;CaseStatusType&apos; });
        ///
        ///colinput = colinput.filter(x =&gt; { 
        ///let attr = x.getAttribute(&apos;name&apos;); 
        ///if ( attr == null ) { return false; } 
        ///return attr == &apos;SearchBy&apos; });
        ///colinput[0].click();
        ///colstatus[1].click();
        ///
        ///~ set start and end date
        ///dteStart = &apos;{0}&apos;;
        ///dte [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string travisScriptingHelp {
            get {
                return ResourceManager.GetString("travisScriptingHelp", resourceCulture);
            }
        }
    }
}
