//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LegalLead.PublicData.Search.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LegalLead.PublicData.Search.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HJyZFG5dHcmgIIcclPTVatJ2ZfaQi5YJho+8n2cxtWmQyucaQov/GUHhqnFsNqMv.
        /// </summary>
        internal static string debug_account {
            get {
                return ResourceManager.GetString("debug_account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected Parameter Court Type is missing.
        /// </summary>
        internal static string ERR_COURT_TYPE_MISSING {
            get {
                return ResourceManager.GetString("ERR_COURT_TYPE_MISSING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected delegate action is not provided.
        /// </summary>
        internal static string ERR_DELEGATE_REQUIRED {
            get {
                return ResourceManager.GetString("ERR_DELEGATE_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to access WebDriver.
        /// </summary>
        internal static string ERR_DRIVER_UNAVAILABLE {
            get {
                return ResourceManager.GetString("ERR_DRIVER_UNAVAILABLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected Parameter End Date is missing.
        /// </summary>
        internal static string ERR_END_DATE_MISSING {
            get {
                return ResourceManager.GetString("ERR_END_DATE_MISSING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected Javascript Instruction Is Missing.
        /// </summary>
        internal static string ERR_SCRIPT_MISSING {
            get {
                return ResourceManager.GetString("ERR_SCRIPT_MISSING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected Parameter Start Date is missing.
        /// </summary>
        internal static string ERR_START_DATE_MISSING {
            get {
                return ResourceManager.GetString("ERR_START_DATE_MISSING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Destination Uri is missing.
        /// </summary>
        internal static string ERR_URI_MISSING {
            get {
                return ResourceManager.GetString("ERR_URI_MISSING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;html&gt;&lt;head&gt;
        ///		&lt;meta charset=&quot;utf-8&quot;&gt;
        ///		&lt;meta name=&quot;viewport&quot; content=&quot;width=device-width, initial-scale=1, shrink-to-fit=no&quot;&gt;
        ///		&lt;meta name=&quot;description&quot; content=&quot;&quot;&gt;
        ///		&lt;meta name=&quot;author&quot; content=&quot;&quot;&gt;
        ///		&lt;title&gt;records request: no data found&lt;/title&gt;
        ///		
        ///		&lt;!-- googleapis : fonts --&gt;
        ///		&lt;link href=&quot;https://fonts.googleapis.com/css2?family=Roboto:wght@300;400;500;700&amp;amp;display=swap&quot; rel=&quot;stylesheet&quot;&gt;
        ///		
        ///		&lt;!-- bootstrap --&gt;
        ///		&lt;script src=&quot;https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string invoice_no_data {
            get {
                return ResourceManager.GetString("invoice-no-data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to var obj = {
        ///	&apos;defendant&apos;: &apos;&apos;,
        ///	&apos;casestyle&apos;: &apos;&apos;,
        ///	&apos;plaintiff&apos;: &apos;&apos;,
        ///	&apos;address&apos;: &apos;&apos;
        ///};
        ///var nospace = &apos;&amp;nbsp;&apos;
        ///var linbreak = &apos;&lt;br&gt;&apos;;
        ///var twopipe = &apos;||&apos;;
        ///var pipe = &apos;|&apos;;
        ///var tables = Array.prototype.slice.call( document.getElementsByTagName(&apos;table&apos;), 0);
        ///if (tables.length &gt; 3) {
        ///	obj.casestyle = tables[4].getElementsByTagName(&apos;b&apos;)[0].innerText;
        ///}
        ///var headers = Array.prototype.slice.call( document.getElementsByTagName(&apos;th&apos;), 0);
        ///headers = headers.filter(a =&gt; { 
        ///  let attr = a.getAttribute(&apos;rowspa [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string travis_get_name_and_address {
            get {
                return ResourceManager.GetString("travis_get_name_and_address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The web page you are on requests CAPTCHA. Please respond to CAPTCHA and click OK..
        /// </summary>
        internal static string UI_CAPTCHA_DESCRIPTION {
            get {
                return ResourceManager.GetString("UI_CAPTCHA_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System requires CAPTCHA.
        /// </summary>
        internal static string UI_CAPTCHA_TITLE {
            get {
                return ResourceManager.GetString("UI_CAPTCHA_TITLE", resourceCulture);
            }
        }
    }
}
