# This workflow will build a .NET framework project(s)
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: CI .NET Framework Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-2019
    strategy:
      matrix:
        dotnet-version: [ '6.0.x' ]
    env:
        SOLUTION_NAME: Thompson.RecordSearch.Core.sln
        TEST_FILE_NAME: "test-results-${{ matrix.dotnet-version }}"
        REPORT_FILE_NAME: "test-results-${{ matrix.dotnet-version }}.md"


    steps:
    - uses: actions/checkout@v2

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1

    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1.0.5
      
    - name: setup-msbuild
      uses: microsoft/setup-msbuild@v1.1

    - name: setup-liquid-test-reports
      run: dotnet tool install --global LiquidTestReports.Cli --version 1.4.3-beta

    - name: Restore Packages
      run: dotnet restore ${{ env.SOLUTION_NAME }}

    - name: Build solution
      run: dotnet build ${{ env.SOLUTION_NAME }} -c Release --no-restore

    - name: Test with dotnet
      run: dotnet test ${{ env.SOLUTION_NAME }} --logger trx -c Release --no-restore --results-directory ${{ env.TEST_FILE_NAME }}

    - name: Upload dotnet test results
      uses: actions/upload-artifact@v3
      with:
        name: dotnet-results-${{ matrix.dotnet-version }}
        path: ${{ env.TEST_FILE_NAME }}
      # Use always() to always run this step to publish test results when there are test failures
      if: ${{ always() }}

    - uses: actions/download-artifact@v3
      id: download
      with:
        name: dotnet-results-${{ matrix.dotnet-version }}
        path: ${{ env.TEST_FILE_NAME }}