# This workflow will build a .NET framework project(s)
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: CI .NET Framework Branch Build

on:
  push:
    branches-ignore:
      - main
      - releases

jobs:
  build:
    runs-on: windows-latest
    timeout-minutes: 15
    env:
        SOLUTION_NAME: Thompson.RecordSearch.Core.sln
        TEST_FILE_NAME: "test-results-${{ matrix.dotnet-version }}"
        REPORT_FILE_NAME: "test-results-${{ matrix.dotnet-version }}.md"
        NET_VERSION: "8.0.x"
        NUGET_CERT_REVOCATION_MODE: offline


    steps:
    - uses: actions/checkout@v4

    - name: setup-liquid-test-reports
      run: dotnet tool install --global LiquidTestReports.Cli --version 1.4.3-beta

    - name: Test with dotnet
      run: dotnet test ${{ env.SOLUTION_NAME }} --logger trx -c Release --results-directory ${{ env.TEST_FILE_NAME }} --filter 'FullyQualifiedName!~UnitTests'

    - name: Upload dotnet test results
      uses: actions/upload-artifact@v3
      with:
        name: dotnet-results-${{ matrix.dotnet-version }}
        path: ${{ env.TEST_FILE_NAME }}
      # Use always() to always run this step to publish test results when there are test failures
      if: ${{ always() }}

    - uses: actions/download-artifact@v3
      id: download
      with:
        name: dotnet-results-${{ matrix.dotnet-version }}
        path: ${{ env.TEST_FILE_NAME }}